### ISSUE TITLE
operating principle "enableUnixPaths"

### ISSUE THREAD

**Issue by smarkusg** [AmigaLabs/clib4#177]
Hi 

I have a question regarding the lack of "libunix" in clib4.
What is the principle of enableUnixPaths() ?
I found one example of its use in - > https://raw.githubusercontent.com/AmigaLabs/clib4/master/test_programs/misc/dev_random.c
does this only work within a program/function ? 
Do I also need to use this in clib4 in the dependent libraries compiled for clib4 "enableUnixPaths() ?

For the whole program it works to create a ".unix" file in PROGDIR . 

Adding enableUnixPaths() in main() works on separate libraries ?
With "newlib", setting "-lunix" when linking works. Can "unixpatch" be set without using the ".unix" file?

<a href="https://ibb.co/GC0RC3g"><img src="https://i.ibb.co/GC0RC3g/lg.jpg" alt="lg" border="0"></a>

Thank you for your help

**Comment by afxgroup** [comment]
You don't need to add enablUnixPaths in every library. Just add the .unix file in the exe need to use the unix path
