### ISSUE TITLE
sem_t is not defined in semaphore.h

### ISSUE THREAD

**Issue by 3246251196** [AmigaLabs/clib4#180]
In a cloned clib4 (master)
`
cd test_programs/threads && ppc-amigaos-gcc -o sem semaphore_test.c -mcrt=clib4
`
Leads to:

```
semaphore_test.c:8:7: error: storage size of ‘mutex’ isn’t known
    8 | sem_t mutex;
      |       ^~~~~

```
Said header file shall define this type.

**Comment by 3246251196** [comment]
@afxgroup 
Hi. No. I have now fixed it in my initial post.

**Comment by afxgroup** [comment]
Well, i've tried with beta10 and it is working. Maybe it is time to merge it into master?

**Comment by 3246251196** [comment]
@afxgroup yep. It is in beta10. Any reason why not to merge? Is it worth running a full build of adtools x compiler to ensure clib4 does not cause any build issues first?

**Comment by 3246251196** [comment]
beta10 has fixed this. We await for it to be merged into master.
