### ISSUE TITLE
Include both the branch and commitid in the VERSTAG

### ISSUE THREAD

**Issue by 3246251196** [AmigaLabs/clib4#197]
Right now when a commit is made we have, for example:
```
#define VERS            "clib4.library 1.0.0"
#define VSTRING            "clib4.library 1.0.0 (26.07.2024)\r\n"
#define VERSTAG            "\0$VER: clib4.library 1.0.0 (26.07.2024)"
```
The issue is that someone may make 25 commits in one day. If there is a bug then we need to be able to clone the precise version of code. It would be useful to add the branch and commitid so it looked something like:
```
#define VERS            "clib4.library 1.0.0"
#define VSTRING            "clib4.library 1.0.0 (26.07.2024)\r\n"
#define VERSTAG            "\0$VER: clib4.library 1.0.0 (26.07.2024) (deadbeef beta10)"
```
Notice the "deadbeef beta10" added in the parenthesis.

The point is, given a distribution of clib4, it should be possible to find out which branch and commitid created it.

**Comment by afxgroup** [comment]
Fixed in master
