### ISSUE TITLE
Consider splitting stubs.o into a stubs_<function>.o to reduce footprint size of final linked binary

### ISSUE THREAD

**Issue by 3246251196** [AmigaLabs/clib4#229]
Is there a reason this is not done?

- build a simple hello world program with -Wl,--verbose. See that stubs.o is linked from the libc.a - see the size of stubs.o.
- do the same with newlib and notice that only the necessary stubs_<function>.o is used.
- compare the size of the binaries.

**Comment by afxgroup** [comment]
I've used one single file just to make compilation a lot faster. But if this is an issue we can change it. No problem

**Comment by 3246251196** [comment]
I started a branch: https://github.com/AmigaLabs/clib4/tree/split_stubs
Just an initial test.

**Comment by afxgroup** [comment]
Merged
